#Created by UFT Digital Lab at Thu Sep 18 16:30:25 BRT 2025
#Thu Sep 18 16:30:25 BRT 2025
DEVICE_ID=00008101-000931D81EE9003A
HTTP_PROXY_HOST=
HTTP_PROXY_PORT=
SERVER_HOST=mobilecenter.net.bradesco.com.br
SERVER_PORT=443
SERVER_USER=m497913
TENANT_ID=999999999
USE_SSL=true
